package form_utama;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.FlowLayout;
import java.awt.Font;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.io.File;
import java.nio.file.Files;

/**
 *
 * @author acer
 */
public class UserKasir extends javax.swing.JPanel {

    private JFileChooser fileChooser;
    private JFileChooser fileChooser1;
    Config koneksi = new Config();
    private boolean fungsi = false;
    private boolean fungsi1 = false;
    private File selectedFile;
    private File selectedFile1;

    /**
     * Creates new form UserKasir
     */
    public UserKasir() {
        initComponents();
        //btn_gambar.setBackground(new Color(0, 0, 0, 0,));
        try {
            kasir1();
            kasir2();
            
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Owner1 = new javax.swing.JButton();
        Owner2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        text_alamat = new javax.swing.JTextField();
        text_gambar = new javax.swing.JLabel();
        text_edit = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_gambar = new javax.swing.JButton();
        t_path = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t_path1 = new javax.swing.JTextField();
        text_pw = new javax.swing.JPasswordField();
        btn_gambar1 = new javax.swing.JButton();
        text_pw1 = new javax.swing.JPasswordField();
        text_edit1 = new javax.swing.JLabel();
        text_no1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text_gambar1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        text_alamat1 = new javax.swing.JTextField();
        text_username1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        text_nama1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panel_utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 192, 239));
        jLabel10.setText("DATA KASIR");
        panel_utama.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        Owner1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Owner1.setForeground(new java.awt.Color(164, 192, 239));
        Owner1.setText("Kasir");
        Owner1.setEnabled(false);
        Owner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Owner1ActionPerformed(evt);
            }
        });
        panel_utama.add(Owner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        Owner2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Owner2.setForeground(new java.awt.Color(164, 192, 239));
        Owner2.setText("Owner");
        Owner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Owner2ActionPerformed(evt);
            }
        });
        panel_utama.add(Owner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 192, 239));
        jLabel3.setText("Nama");
        jPanel3.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 40, -1, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 192, 239));
        jLabel4.setText("Password");
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 193, -1, -1));

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(431, 994, -1, -1));

        text_nama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_nama.setEnabled(false);
        text_nama.setMaximumSize(new java.awt.Dimension(64, 22));
        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });
        jPanel3.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(514, 42, 286, 32));

        text_alamat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_alamat.setEnabled(false);
        text_alamat.setMaximumSize(new java.awt.Dimension(64, 22));
        text_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamatActionPerformed(evt);
            }
        });
        jPanel3.add(text_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 143, 284, 32));

        text_gambar.setMaximumSize(new java.awt.Dimension(300, 300));
        text_gambar.setMinimumSize(new java.awt.Dimension(300, 300));
        text_gambar.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.add(text_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 40, -1, -1));

        text_edit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        text_edit.setForeground(new java.awt.Color(164, 192, 239));
        text_edit.setText("EDIT");
        text_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_editMouseClicked(evt);
            }
        });
        jPanel3.add(text_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(742, 387, -1, -1));

        text_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_username.setEnabled(false);
        text_username.setMaximumSize(new java.awt.Dimension(64, 22));
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        jPanel3.add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(516, 91, 284, 32));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 192, 239));
        jLabel7.setText("Username");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 89, -1, -1));

        text_no.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_no.setEnabled(false);
        text_no.setMaximumSize(new java.awt.Dimension(64, 22));
        text_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_noActionPerformed(evt);
            }
        });
        jPanel3.add(text_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(572, 244, 228, 32));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(164, 192, 239));
        jLabel8.setText("Nomor Telepon");
        jPanel3.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 242, -1, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(164, 192, 239));
        jLabel9.setText("Alamat");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(343, 141, -1, -1));

        btn_gambar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/button.png"))); // NOI18N
        btn_gambar.setEnabled(false);
        btn_gambar.setOpaque(true);
        btn_gambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gambarActionPerformed(evt);
            }
        });
        jPanel3.add(btn_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 340, -1, 40));

        t_path.setEnabled(false);
        jPanel3.add(t_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 340, 243, 37));

        jLabel1.setText("_________________________________________________________________________________________________________________________________________________________________");
        jPanel3.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 417, 778, -1));

        t_path1.setEnabled(false);
        jPanel3.add(t_path1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 803, 243, 37));

        text_pw.setEnabled(false);
        jPanel3.add(text_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 200, 280, 30));

        btn_gambar1.setText("jButton1");
        btn_gambar1.setEnabled(false);
        btn_gambar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gambar1ActionPerformed(evt);
            }
        });
        jPanel3.add(btn_gambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 803, 39, 37));

        text_pw1.setEnabled(false);
        jPanel3.add(text_pw1, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 630, 280, 30));

        text_edit1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        text_edit1.setForeground(new java.awt.Color(164, 192, 239));
        text_edit1.setText("EDIT");
        text_edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_edit1MouseClicked(evt);
            }
        });
        jPanel3.add(text_edit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 807, -1, -1));

        text_no1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_no1.setEnabled(false);
        text_no1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_no1ActionPerformed(evt);
            }
        });
        jPanel3.add(text_no1, new org.netbeans.lib.awtextra.AbsoluteConstraints(564, 681, 228, 32));

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(164, 192, 239));
        jLabel11.setText("Nomor Telepon");
        jPanel3.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 679, -1, -1));

        text_gambar1.setMaximumSize(new java.awt.Dimension(300, 300));
        text_gambar1.setMinimumSize(new java.awt.Dimension(300, 300));
        text_gambar1.setPreferredSize(new java.awt.Dimension(300, 300));
        jPanel3.add(text_gambar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 474, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(164, 192, 239));
        jLabel6.setText("Password");
        jPanel3.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 627, -1, -1));

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(164, 192, 239));
        jLabel12.setText("Alamat");
        jPanel3.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 575, -1, -1));

        text_alamat1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_alamat1.setEnabled(false);
        text_alamat1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_alamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamat1ActionPerformed(evt);
            }
        });
        jPanel3.add(text_alamat1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 577, 284, 32));

        text_username1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_username1.setEnabled(false);
        text_username1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_username1ActionPerformed(evt);
            }
        });
        jPanel3.add(text_username1, new org.netbeans.lib.awtextra.AbsoluteConstraints(508, 525, 284, 32));

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(164, 192, 239));
        jLabel13.setText("Username");
        jPanel3.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 523, -1, -1));

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(164, 192, 239));
        jLabel14.setText("Nama");
        jPanel3.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(335, 474, -1, -1));

        text_nama1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_nama1.setEnabled(false);
        text_nama1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nama1ActionPerformed(evt);
            }
        });
        jPanel3.add(text_nama1, new org.netbeans.lib.awtextra.AbsoluteConstraints(506, 476, 286, 32));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/batik azure.png"))); // NOI18N
        jLabel15.setPreferredSize(new java.awt.Dimension(1025, 1377));
        jPanel3.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 650));

        jScrollPane1.setViewportView(jPanel3);

        panel_utama.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 870, 560));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/batik azure.png"))); // NOI18N
        panel_utama.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -20, 990, 810));

        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

  

    private void Owner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Owner1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(new UserKasir());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_Owner1ActionPerformed

    private void Owner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Owner2ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(new UserOwner());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_Owner2ActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamatActionPerformed

    private void text_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_editMouseClicked
        // TODO add your handling code here:
        if (fungsi == false) {
            fungsi = true;
            text_edit.setText("SIMPAN");

            text_nama.setEnabled(true);
            text_username.setEnabled(true);
            text_alamat.setEnabled(true);
            text_pw.setEnabled(true);
            text_no.setEnabled(true);
            btn_gambar.setEnabled(true);
            t_path.setEnabled(true);
        } else {
            fungsi = false;
            editdata1();
            text_edit.setText("EDIT");
            text_nama.setEnabled(false);
            text_username.setEnabled(false);
            text_alamat.setEnabled(false);
            text_pw.setEnabled(false);
            text_no.setEnabled(false);
            btn_gambar.setEnabled(false);
            t_path.setEnabled(false);
        }
    }//GEN-LAST:event_text_editMouseClicked

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_noActionPerformed

    private void btn_gambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gambarActionPerformed
        // TODO add your handling code here:
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png");
        fileChooser.addChoosableFileFilter(imageFilter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            t_path.setText(path);
    }//GEN-LAST:event_btn_gambarActionPerformed
        prosesGambar(selectedFile);
    }
    private void btn_gambar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gambar1ActionPerformed
        // TODO add your handling code here:
        fileChooser1 = new JFileChooser();
        fileChooser1.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png");
        fileChooser1.addChoosableFileFilter(imageFilter);
        int result = fileChooser1.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile1 = fileChooser1.getSelectedFile();
            String path = selectedFile1.getAbsolutePath();
            t_path1.setText(path);
        }
        prosesGambar1(selectedFile1);
    }//GEN-LAST:event_btn_gambar1ActionPerformed

    private void text_edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_edit1MouseClicked
        // TODO add your handling code here:
        if (fungsi1 == false) {
            fungsi1 = true;
            text_edit1.setText("SIMPAN");
            text_nama1.setEnabled(true);
            text_username1.setEnabled(true);
            text_alamat1.setEnabled(true);
            text_pw1.setEnabled(true);
            text_no1.setEnabled(true);
            btn_gambar1.setEnabled(true);
            t_path1.setEnabled(true);
        } else {
            fungsi1 = false;
            editdata2();
            text_edit1.setText("EDIT");

            text_nama1.setEnabled(false);
            text_username1.setEnabled(false);
            text_alamat1.setEnabled(false);
            text_pw1.setEnabled(false);
            text_no1.setEnabled(false);
            btn_gambar1.setEnabled(false);
            t_path1.setEnabled(false);
        }
    }//GEN-LAST:event_text_edit1MouseClicked

    private void text_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_no1ActionPerformed

    private void text_alamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamat1ActionPerformed

    private void text_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_username1ActionPerformed

    private void text_nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nama1ActionPerformed

    public void editdata1() {

        try {
            java.sql.Connection con = (Connection) Config.ConfigDB();

            PreparedStatement checkbahan = con.prepareStatement(
                    "SELECT * FROM user where id_user = '2'"
            );

            ResultSet rsuser = checkbahan.executeQuery();

            if (rsuser.next()) {
                String nama = text_nama.getText();
                String username = text_username.getText();
                String alamat = text_alamat.getText();
                String password = text_pw.getText();
                String no = text_no.getText();
                PreparedStatement updatemenu = koneksi.ConfigDB().prepareStatement("UPDATE user SET nama_lengkap = ?,"
                        + "username = ?,"
                        + "alamat = ?,"
                        + "password = ?,"
                        + "phone = ?"
                        + "WHERE id_user = '2'");
                updatemenu.setString(1, nama);
                updatemenu.setString(2, username);
                updatemenu.setString(3, alamat);
                updatemenu.setString(4, password);
                updatemenu.setString(5, no);
                updatemenu.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                kasir1();
                panel_utama.removeAll();
                panel_utama.add(new UserKasir());
                panel_utama.repaint();
                panel_utama.revalidate();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error mengupdate data: " + e.getMessage());
        }

    }

    public void editdata2() {

        try {
            java.sql.Connection con = (Connection) Config.ConfigDB();

            PreparedStatement checkbahan = con.prepareStatement(
                    "SELECT * FROM user where id_user = '3'"
            );

            ResultSet rsuser = checkbahan.executeQuery();

            if (rsuser.next()) {
                String nama = text_nama1.getText();
                String username = text_username1.getText();
                String alamat = text_alamat1.getText();
                String password = text_pw1.getText();
                String no = text_no1.getText();
                PreparedStatement updatemenu = koneksi.ConfigDB().prepareStatement("UPDATE user SET "
                        + "nama_lengkap = ?,"
                        + "username = ?,"
                        + "alamat = ?,"
                        + "password = ?,"
                        + "phone = ?"
                        + "WHERE id_user = '3'");
                updatemenu.setString(1, nama);
                updatemenu.setString(2, username);
                updatemenu.setString(3, alamat);
                updatemenu.setString(4, password);
                updatemenu.setString(5, no);
                updatemenu.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                kasir2();
                panel_utama.removeAll();
                panel_utama.add(new UserKasir());
                panel_utama.repaint();
                panel_utama.revalidate();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error mengupdate data: " + e.getMessage());
        }

    }

    private void prosesGambar(File file) {
        try {
            // Baca file sebagai byte array
            byte[] imageBytes = Files.readAllBytes(file.toPath());

            // Buat ImageIcon untuk preview
            ImageIcon imageIcon = new ImageIcon(imageBytes);

            // Resize gambar jika terlalu besar
            if (imageIcon.getIconWidth() > 300) {
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(300, -1, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
            }

            // Tampilkan preview (opsional)
            tampilkanPreview(imageIcon);

            // Simpan ke database
            simpanKeDatabase(imageBytes, file.getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error memproses gambar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void prosesGambar1(File file) {
        try {
            // Baca file sebagai byte array
            byte[] imageBytes = Files.readAllBytes(file.toPath());

            // Buat ImageIcon untuk preview
            ImageIcon imageIcon = new ImageIcon(imageBytes);

            // Resize gambar jika terlalu besar
            if (imageIcon.getIconWidth() > 300) {
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(300, -1, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
            }

            // Tampilkan preview (opsional)
            tampilkanPreview1(imageIcon);

            // Simpan ke database
            simpanKeDatabase1(imageBytes, file.getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error memproses gambar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tampilkanPreview(ImageIcon imageIcon) {
        text_gambar = new JLabel(imageIcon);
    }

    private void tampilkanPreview1(ImageIcon imageIcon) {
        text_gambar1 = new JLabel(imageIcon);
    }

    private void simpanKeDatabase(byte[] imageBytes, String fileName) {
        // Gunakan try-with-resources untuk koneksi database
        try (
                Connection conn = (Connection) Config.ConfigDB(); PreparedStatement pstmt = conn.prepareStatement("UPDATE user SET photo = ? WHERE id_user = '2'")) {

            pstmt.setBytes(1, imageBytes);
// Pastikan currentId sudah dideklarasikan

            int result = pstmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "Gambar berhasil disimpan Ke Database",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                try {
                    kasir1();
                } catch (Exception e) {
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error menyimpan ke database: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void simpanKeDatabase1(byte[] imageBytes, String fileName) {
        // Gunakan try-with-resources untuk koneksi database
        try (
                Connection conn = (Connection) Config.ConfigDB(); PreparedStatement pstmt = conn.prepareStatement("UPDATE user SET photo = ? WHERE id_user = '3'")) {

            pstmt.setBytes(1, imageBytes);
// Pastikan currentId sudah dideklarasikan

            int result = pstmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "Gambar berhasil disimpan Ke Database",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                try {
                    kasir2();
                } catch (Exception e) {
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error menyimpan ke database: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        prosesGambar(selectedFile);
    }

    private void kasir1() throws IOException {
        try {
            String query = "SELECT * FROM user where id_user = '2'";
            // Ganti nama_tabel dan kolom_stok sesuai dengan struktur database Anda
            java.sql.Connection con = (Connection) Config.ConfigDB();
            //java.sql.ResultSet rs = pst.executeQuery(sql);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String s_nama = rs.getString("nama_lengkap");
                String username = rs.getString("username");
                String alamat = rs.getString("alamat");
                String pw = rs.getString("password");
                String no_telepon = rs.getString("phone");
                text_nama.setText(s_nama);
                text_username.setText(username);
                text_alamat.setText(alamat);
                text_pw.setText(pw);
                text_no.setText(no_telepon);

                byte[] imgData = rs.getBytes("photo"); // Sesuaikan nama kolom gambar di database
                if (imgData != null) {
                    // Konversi data gambar menjadi ImageIcon
                    InputStream is = new ByteArrayInputStream(imgData);
                    BufferedImage bufferedImage = ImageIO.read(is);
                    ImageIcon icon = new ImageIcon(bufferedImage);

                    // Tampilkan gambar pada JLabel
                    text_gambar.setIcon(icon); // Pastikan `gambar_1` adalah JLabel
                } else {
                    text_gambar.setText("Gambar tidak tersedia");
                }
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error mengambil data: " + e.getMessage());
        }
    }

    private void kasir2() throws IOException {
        try {
            String query = "SELECT * FROM user where id_user = '3'";
            // Ganti nama_tabel dan kolom_stok sesuai dengan struktur database Anda
            java.sql.Connection con = (Connection) Config.ConfigDB();
            //java.sql.ResultSet rs = pst.executeQuery(sql);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String nama = rs.getString("nama_lengkap");
                String username = rs.getString("username");
                String alamat = rs.getString("alamat");
                String pw = rs.getString("password");
                String no_telepon = rs.getString("phone");
                text_nama1.setText(nama);
                text_username1.setText(username);
                text_alamat1.setText(alamat);
                text_pw1.setText(pw);
                text_no1.setText(no_telepon);

                byte[] imgData = rs.getBytes("photo"); // Sesuaikan nama kolom gambar di database
                if (imgData != null) {
                    // Konversi data gambar menjadi ImageIcon
                    InputStream is = new ByteArrayInputStream(imgData);
                    BufferedImage bufferedImage = ImageIO.read(is);
                    ImageIcon icon = new ImageIcon(bufferedImage);

                    // Tampilkan gambar pada JLabel
                    text_gambar1.setIcon(icon); // Pastikan `gambar_1` adalah JLabel
                } else {
                    text_gambar1.setText("Gambar tidak tersedia");
                }
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error mengambil data: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Owner1;
    private javax.swing.JButton Owner2;
    private javax.swing.JButton btn_gambar;
    private javax.swing.JButton btn_gambar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JTextField t_path;
    private javax.swing.JTextField t_path1;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JTextField text_alamat1;
    private javax.swing.JLabel text_edit;
    private javax.swing.JLabel text_edit1;
    private javax.swing.JLabel text_gambar;
    private javax.swing.JLabel text_gambar1;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nama1;
    private javax.swing.JTextField text_no;
    private javax.swing.JTextField text_no1;
    private javax.swing.JPasswordField text_pw;
    private javax.swing.JPasswordField text_pw1;
    private javax.swing.JTextField text_username;
    private javax.swing.JTextField text_username1;
    // End of variables declaration//GEN-END:variables
}
