package form_utama;


import java.awt.Image;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.io.File;
import java.nio.file.Files;

public class UserOwner extends javax.swing.JPanel {

    private JFileChooser fileChooser;
    Config koneksi = new Config();
    private boolean fungsi = false;
    private File selectedFile;

    /**
     * Creates new form UserOwner
     */
    public UserOwner() {
        initComponents();
        try {
            owner();
        } catch (Exception e) {
        }
    }

    private void owner() throws IOException {
        try {
            String query = "SELECT * FROM user where posisi = 'Owner'";
            // Ganti nama_tabel dan kolom_stok sesuai dengan struktur database Anda
            java.sql.Connection con = (Connection) Config.ConfigDB();
            //java.sql.ResultSet rs = pst.executeQuery(sql);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String nama = rs.getString("nama");
                String username = rs.getString("username");
                String alamat = rs.getString("alamat");
                String pw = rs.getString("password");
                String no_telepon = rs.getString("phone");

                text_nama.setText(nama);
                text_username.setText(username);
                text_alamat.setText(alamat);
                text_pw.setText(pw);
                text_no.setText(no_telepon);

                byte[] imgData = rs.getBytes("foto"); // Sesuaikan nama kolom gambar di database
                if (imgData != null) {
                    // Konversi data gambar menjadi ImageIcon
                    InputStream is = new ByteArrayInputStream(imgData);
                    BufferedImage bufferedImage = ImageIO.read(is);
                    ImageIcon icon = new ImageIcon(bufferedImage);

                    // Tampilkan gambar pada JLabel
                    text_gambar.setIcon(icon); // Pastikan `gambar_1` adalah JLabel
                } else {
                    text_gambar.setText("Gambar tidak tersedia");
                }
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error mengambil data: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Owner2 = new javax.swing.JButton();
        Owner1 = new javax.swing.JButton();
        text_gambar = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        text_alamat = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        text_pw = new javax.swing.JTextField();
        text_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        text_edit = new javax.swing.JLabel();
        btn_gambar = new javax.swing.JButton();
        t_path = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        panel_utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 192, 239));
        jLabel10.setText("DATA OWNER");
        panel_utama.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        Owner2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Owner2.setForeground(new java.awt.Color(164, 192, 239));
        Owner2.setText("Owner");
        Owner2.setEnabled(false);
        Owner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Owner2ActionPerformed(evt);
            }
        });
        panel_utama.add(Owner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, -1));

        Owner1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Owner1.setForeground(new java.awt.Color(164, 192, 239));
        Owner1.setText("Kasir");
        Owner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Owner1ActionPerformed(evt);
            }
        });
        panel_utama.add(Owner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        text_gambar.setMaximumSize(new java.awt.Dimension(300, 300));
        text_gambar.setMinimumSize(new java.awt.Dimension(300, 300));
        text_gambar.setPreferredSize(new java.awt.Dimension(300, 300));
        panel_utama.add(text_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 240, -1, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(164, 192, 239));
        jLabel3.setText("Nama");
        panel_utama.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 290, -1, -1));

        text_nama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_nama.setEnabled(false);
        text_nama.setMaximumSize(new java.awt.Dimension(64, 22));
        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });
        panel_utama.add(text_nama, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 290, 320, -1));

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(164, 192, 239));
        jLabel7.setText("Username");
        panel_utama.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        text_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_username.setEnabled(false);
        text_username.setMaximumSize(new java.awt.Dimension(64, 22));
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });
        panel_utama.add(text_username, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 240, 320, -1));

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(164, 192, 239));
        jLabel9.setText("Alamat");
        panel_utama.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 340, -1, -1));

        text_alamat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_alamat.setEnabled(false);
        text_alamat.setMaximumSize(new java.awt.Dimension(64, 22));
        text_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamatActionPerformed(evt);
            }
        });
        panel_utama.add(text_alamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 340, 320, -1));

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(164, 192, 239));
        jLabel4.setText("Password");
        panel_utama.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 390, -1, -1));

        text_pw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_pw.setEnabled(false);
        text_pw.setMaximumSize(new java.awt.Dimension(64, 22));
        text_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pwActionPerformed(evt);
            }
        });
        panel_utama.add(text_pw, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 390, 320, -1));

        text_no.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_no.setEnabled(false);
        text_no.setMaximumSize(new java.awt.Dimension(64, 22));
        text_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_noActionPerformed(evt);
            }
        });
        panel_utama.add(text_no, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 440, 280, -1));

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(164, 192, 239));
        jLabel8.setText("Nomor Telepon");
        panel_utama.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 440, -1, -1));

        text_edit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        text_edit.setForeground(new java.awt.Color(164, 192, 239));
        text_edit.setText("EDIT");
        text_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_editMouseClicked(evt);
            }
        });
        panel_utama.add(text_edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 550, -1, -1));

        btn_gambar.setBackground(new java.awt.Color(204, 204, 204));
        btn_gambar.setText("jButton1");
        btn_gambar.setEnabled(false);
        btn_gambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gambarActionPerformed(evt);
            }
        });
        panel_utama.add(btn_gambar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 560, 30, 30));

        t_path.setEditable(false);
        t_path.setBackground(new java.awt.Color(204, 204, 204));
        t_path.setEnabled(false);
        panel_utama.add(t_path, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 560, 230, 30));
        panel_utama.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 770));

        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void Owner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Owner1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(new UserKasir());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_Owner1ActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamatActionPerformed

    private void text_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pwActionPerformed

    private void text_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_noActionPerformed

    private void text_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_editMouseClicked
        // TODO add your handling code here:
        if (fungsi == false) {
            fungsi = true;
            text_edit.setText("SIMPAN");
            text_nama.setEnabled(true);
            text_username.setEnabled(true);
            text_alamat.setEnabled(true);
            text_pw.setEnabled(true);
            text_no.setEnabled(true);
            btn_gambar.setEnabled(true);
            t_path.setEnabled(true);
        } else {
            fungsi = false;
            editdata();
            text_edit.setText("EDIT");

            text_nama.setEnabled(false);
            text_username.setEnabled(false);
            text_alamat.setEnabled(false);
            text_pw.setEnabled(false);
            text_no.setEnabled(false);
            btn_gambar.setEnabled(false);
            t_path.setEnabled(false);
        }

    }//GEN-LAST:event_text_editMouseClicked

    private void simpanKeDatabase(byte[] imageBytes, String fileName) {
        // Gunakan try-with-resources untuk koneksi database
        try (
                Connection conn = (Connection) Config.ConfigDB(); PreparedStatement pstmt = conn.prepareStatement("UPDATE user SET foto = ?WHERE posisi = 'Admin'")) {

            pstmt.setBytes(1, imageBytes);
// Pastikan currentId sudah dideklarasikan

            int result = pstmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "Gambar berhasil disimpan Ke Database",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                try {
                    owner();
                } catch (Exception e) {
                }
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error menyimpan ke database: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tampilkanPreview(ImageIcon imageIcon) {
        text_gambar = new JLabel(imageIcon);
    }

    private void prosesGambar(File file) {
        try {
            // Baca file sebagai byte array
            byte[] imageBytes = Files.readAllBytes(file.toPath());

            // Buat ImageIcon untuk preview
            ImageIcon imageIcon = new ImageIcon(imageBytes);

            // Resize gambar jika terlalu besar
            if (imageIcon.getIconWidth() > 300) {
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(300, -1, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
            }

            // Tampilkan preview (opsional)
            tampilkanPreview(imageIcon);

            // Simpan ke database
            simpanKeDatabase(imageBytes, file.getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error memproses gambar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    public void editdata() {

        try {
            java.sql.Connection con = (Connection) Config.ConfigDB();

            PreparedStatement checkbahan = con.prepareStatement(
                    "SELECT * FROM user where posisi = 'Admin'"
            );

            ResultSet rsuser = checkbahan.executeQuery();

            if (rsuser.next()) {
                String nama = text_nama.getText();
                String username = text_username.getText();
                String alamat = text_alamat.getText();
                String password = text_pw.getText();
                String no = text_no.getText();
                PreparedStatement updatemenu = koneksi.ConfigDB().prepareStatement("UPDATE user SET "
                        + "nama = ?,"
                        + "username = ?,"
                        + "alamat = ?,"
                        + "password = ?,"
                        + "phone = ?"
                        + "WHERE posisi = 'Admin'");
                updatemenu.setString(1, nama);
                updatemenu.setString(2, username);
                updatemenu.setString(3, alamat);
                updatemenu.setString(4, password);
                updatemenu.setString(5, no);
                updatemenu.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                //owner();
                panel_utama.removeAll();
                panel_utama.add(new UserOwner());
                panel_utama.repaint();
                panel_utama.revalidate();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error mengupdate data: " + e.getMessage());
        }

    }

    private void btn_gambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gambarActionPerformed
        // TODO add your handling code here:
        // TODO add your handling code here:
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png");
        fileChooser.addChoosableFileFilter(imageFilter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            t_path.setText(path);
        }
        prosesGambar(selectedFile);
    }//GEN-LAST:event_btn_gambarActionPerformed

    private void Owner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Owner2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Owner2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Owner1;
    private javax.swing.JButton Owner2;
    private javax.swing.JButton btn_gambar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JTextField t_path;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JLabel text_edit;
    private javax.swing.JLabel text_gambar;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_no;
    private javax.swing.JTextField text_pw;
    private javax.swing.JTextField text_username;
    // End of variables declaration//GEN-END:variables
}
