package form_utama;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import java.awt.Image;
import javax.swing.*;
import javax.swing.filechooser.FileNameExtensionFilter;
import java.awt.image.BufferedImage;
import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.io.File;
import java.nio.file.Files;

/**
 *
 * @author acer
 */
public class UserKasir extends javax.swing.JPanel {

    private JFileChooser fileChooser;
    private JFileChooser fileChooser1;
    Config koneksi = new Config();
    private boolean fungsi = false;
    private boolean fungsi1 = false;
    private File selectedFile;
    private File selectedFile1;

    /**
     * Creates new form UserKasir
     */
    public UserKasir() {
        initComponents();
        try {
            kasir1();
            kasir2();
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        Owner1 = new javax.swing.JButton();
        Owner2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        text_nama = new javax.swing.JTextField();
        text_pw = new javax.swing.JTextField();
        text_alamat = new javax.swing.JTextField();
        text_gambar = new javax.swing.JLabel();
        text_edit = new javax.swing.JLabel();
        text_username = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        text_no = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        btn_gambar = new javax.swing.JButton();
        t_path = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        t_path1 = new javax.swing.JTextField();
        btn_gambar1 = new javax.swing.JButton();
        text_edit1 = new javax.swing.JLabel();
        text_no1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        text_gambar1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        text_pw1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        text_alamat1 = new javax.swing.JTextField();
        text_username1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        text_nama1 = new javax.swing.JTextField();

        setLayout(new java.awt.CardLayout());

        panel_utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 30)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(164, 192, 239));
        jLabel10.setText("DATA KASIR");
        panel_utama.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        Owner1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Owner1.setForeground(new java.awt.Color(164, 192, 239));
        Owner1.setText("Kasir");
        Owner1.setEnabled(false);
        Owner1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Owner1ActionPerformed(evt);
            }
        });
        panel_utama.add(Owner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        Owner2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Owner2.setForeground(new java.awt.Color(164, 192, 239));
        Owner2.setText("Owner");
        Owner2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Owner2ActionPerformed(evt);
            }
        });
        panel_utama.add(Owner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 120, -1));

        jLabel3.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel3.setText("Nama");

        jLabel4.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel4.setText("Password");

        jLabel5.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N

        text_nama.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_nama.setEnabled(false);
        text_nama.setMaximumSize(new java.awt.Dimension(64, 22));
        text_nama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_namaActionPerformed(evt);
            }
        });

        text_pw.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_pw.setEnabled(false);
        text_pw.setMaximumSize(new java.awt.Dimension(64, 22));
        text_pw.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pwActionPerformed(evt);
            }
        });

        text_alamat.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_alamat.setEnabled(false);
        text_alamat.setMaximumSize(new java.awt.Dimension(64, 22));
        text_alamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamatActionPerformed(evt);
            }
        });

        text_gambar.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_gambar.setMaximumSize(new java.awt.Dimension(300, 300));
        text_gambar.setMinimumSize(new java.awt.Dimension(300, 300));
        text_gambar.setPreferredSize(new java.awt.Dimension(300, 300));

        text_edit.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        text_edit.setForeground(new java.awt.Color(102, 0, 0));
        text_edit.setText("EDIT");
        text_edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_editMouseClicked(evt);
            }
        });

        text_username.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_username.setEnabled(false);
        text_username.setMaximumSize(new java.awt.Dimension(64, 22));
        text_username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_usernameActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel7.setText("Username");

        text_no.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_no.setEnabled(false);
        text_no.setMaximumSize(new java.awt.Dimension(64, 22));
        text_no.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_noActionPerformed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel8.setText("Nomor Telepon");

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel9.setText("Alamat");

        btn_gambar.setText("jButton1");
        btn_gambar.setEnabled(false);
        btn_gambar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gambarActionPerformed(evt);
            }
        });

        t_path.setEnabled(false);

        jLabel1.setText("_________________________________________________________________________________________________________________________________________________________________");

        t_path1.setEnabled(false);

        btn_gambar1.setText("jButton1");
        btn_gambar1.setEnabled(false);
        btn_gambar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_gambar1ActionPerformed(evt);
            }
        });

        text_edit1.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        text_edit1.setForeground(new java.awt.Color(102, 0, 0));
        text_edit1.setText("EDIT");
        text_edit1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                text_edit1MouseClicked(evt);
            }
        });

        text_no1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_no1.setEnabled(false);
        text_no1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_no1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_no1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel11.setText("Nomor Telepon");

        text_gambar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        text_gambar1.setMaximumSize(new java.awt.Dimension(300, 300));
        text_gambar1.setMinimumSize(new java.awt.Dimension(300, 300));
        text_gambar1.setPreferredSize(new java.awt.Dimension(300, 300));

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel6.setText("Password");

        text_pw1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_pw1.setEnabled(false);
        text_pw1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_pw1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_pw1ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel12.setText("Alamat");

        text_alamat1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_alamat1.setEnabled(false);
        text_alamat1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_alamat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_alamat1ActionPerformed(evt);
            }
        });

        text_username1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_username1.setEnabled(false);
        text_username1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_username1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel13.setText("Username");

        jLabel14.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel14.setText("Nama");

        text_nama1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        text_nama1.setEnabled(false);
        text_nama1.setMaximumSize(new java.awt.Dimension(64, 22));
        text_nama1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                text_nama1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(431, 431, 431)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(735, 735, 735)
                        .addComponent(text_edit))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(t_path1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(btn_gambar1, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(text_edit1))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                            .addComponent(text_gambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(29, 29, 29)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(text_alamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(54, 54, 54)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(text_nama1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(text_username1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGroup(jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addGap(58, 58, 58)
                                    .addComponent(text_pw1, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                    .addComponent(jLabel11)
                                    .addGap(55, 55, 55)
                                    .addComponent(text_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(106, 106, 106)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(t_path, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btn_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(text_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(37, 37, 37)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(text_no, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel4))
                                .addGap(58, 58, 58)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(text_pw, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(text_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(text_nama, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(text_username, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(63, 63, 63))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(text_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_nama, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_username, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_alamat, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_pw, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_no, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_gambar, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t_path, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addComponent(text_edit, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(41, 41, 41)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(text_gambar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_nama1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_alamat1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_pw1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(text_no1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addGap(61, 61, 61)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(jLabel5)
                        .addGap(383, 383, 383))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_gambar1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t_path1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(text_edit1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))))
        );

        jScrollPane1.setViewportView(jPanel3);

        panel_utama.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 870, 610));

        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents

    private void Owner1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Owner1ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(new UserKasir());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_Owner1ActionPerformed

    private void Owner2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Owner2ActionPerformed
        // TODO add your handling code here:
        panel_utama.removeAll();
        panel_utama.add(new UserOwner());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_Owner2ActionPerformed

    private void text_namaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_namaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_namaActionPerformed

    private void text_pwActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pwActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pwActionPerformed

    private void text_alamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamatActionPerformed

    private void text_editMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_editMouseClicked
        // TODO add your handling code here:
        if (fungsi == false) {
            fungsi = true;
            text_edit.setText("SIMPAN");

            text_nama.setEnabled(true);
            text_username.setEnabled(true);
            text_alamat.setEnabled(true);
            text_pw.setEnabled(true);
            text_no.setEnabled(true);
            btn_gambar.setEnabled(true);
            t_path.setEnabled(true);
        } else {
            fungsi = false;
            editdata1();
            text_edit.setText("EDIT");
            text_nama.setEnabled(false);
            text_username.setEnabled(false);
            text_alamat.setEnabled(false);
            text_pw.setEnabled(false);
            text_no.setEnabled(false);
            btn_gambar.setEnabled(false);
            t_path.setEnabled(false);
        }
    }//GEN-LAST:event_text_editMouseClicked

    private void text_usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_usernameActionPerformed

    private void text_noActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_noActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_noActionPerformed

    private void btn_gambarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gambarActionPerformed
        // TODO add your handling code here:
        fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png");
        fileChooser.addChoosableFileFilter(imageFilter);
        int result = fileChooser.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile = fileChooser.getSelectedFile();
            String path = selectedFile.getAbsolutePath();
            t_path.setText(path);
    }//GEN-LAST:event_btn_gambarActionPerformed
        prosesGambar(selectedFile);
    }
    private void btn_gambar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_gambar1ActionPerformed
        // TODO add your handling code here:
        fileChooser1 = new JFileChooser();
        fileChooser1.setCurrentDirectory(new File(System.getProperty("user.home")));
        FileNameExtensionFilter imageFilter = new FileNameExtensionFilter(
                "Image files", "jpg", "jpeg", "png");
        fileChooser1.addChoosableFileFilter(imageFilter);
        int result = fileChooser1.showSaveDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            selectedFile1 = fileChooser1.getSelectedFile();
            String path = selectedFile1.getAbsolutePath();
            t_path1.setText(path);
        }
        prosesGambar1(selectedFile1);
    }//GEN-LAST:event_btn_gambar1ActionPerformed

    private void text_edit1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_text_edit1MouseClicked
        // TODO add your handling code here:
        if (fungsi1 == false) {
            fungsi1 = true;
            text_edit1.setText("SIMPAN");
            text_nama1.setEnabled(true);
            text_username1.setEnabled(true);
            text_alamat1.setEnabled(true);
            text_pw1.setEnabled(true);
            text_no1.setEnabled(true);
            btn_gambar1.setEnabled(true);
            t_path1.setEnabled(true);
        } else {
            fungsi1 = false;
            editdata2();
            text_edit1.setText("EDIT");

            text_nama1.setEnabled(false);
            text_username1.setEnabled(false);
            text_alamat1.setEnabled(false);
            text_pw1.setEnabled(false);
            text_no1.setEnabled(false);
            btn_gambar1.setEnabled(false);
            t_path1.setEnabled(false);
        }
    }//GEN-LAST:event_text_edit1MouseClicked

    private void text_no1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_no1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_no1ActionPerformed

    private void text_pw1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_pw1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_pw1ActionPerformed

    private void text_alamat1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_alamat1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_alamat1ActionPerformed

    private void text_username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_username1ActionPerformed

    private void text_nama1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_text_nama1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_text_nama1ActionPerformed

    public void editdata1() {

        try {
            java.sql.Connection con = (Connection) Config.ConfigDB();

            PreparedStatement checkbahan = con.prepareStatement(
                    "SELECT * FROM user where kd_user = 'KU_02'"
            );

            ResultSet rsuser = checkbahan.executeQuery();

            if (rsuser.next()) {
                String nama = text_nama.getText();
                String username = text_username.getText();
                String alamat = text_alamat.getText();
                String password = text_pw.getText();
                String no = text_no.getText();
                PreparedStatement updatemenu = koneksi.ConfigDB().prepareStatement("UPDATE user SET nama = ?,"
                        + "username = ?,"
                        + "alamat = ?,"
                        + "password = ?,"
                        + "phone = ?"
                        + "WHERE kd_user = 'KU_02'");
                updatemenu.setString(1, nama);
                updatemenu.setString(2, username);
                updatemenu.setString(3, alamat);
                updatemenu.setString(4, password);
                updatemenu.setString(5, no);
                updatemenu.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                kasir1();
                panel_utama.removeAll();
                panel_utama.add(new UserKasir());
                panel_utama.repaint();
                panel_utama.revalidate();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error mengupdate data: " + e.getMessage());
        }

    }

    public void editdata2() {

        try {
            java.sql.Connection con = (Connection) Config.ConfigDB();

            PreparedStatement checkbahan = con.prepareStatement(
                    "SELECT * FROM user where kd_user = 'KU_03'"
            );

            ResultSet rsuser = checkbahan.executeQuery();

            if (rsuser.next()) {
                String nama = text_nama1.getText();
                String username = text_username1.getText();
                String alamat = text_alamat1.getText();
                String password = text_pw1.getText();
                String no = text_no1.getText();
                PreparedStatement updatemenu = koneksi.ConfigDB().prepareStatement("UPDATE user SET "
                        + "nama = ?,"
                        + "username = ?,"
                        + "alamat = ?,"
                        + "password = ?,"
                        + "phone = ?"
                        + "WHERE kd_user = 'KU_03'");
                updatemenu.setString(1, nama);
                updatemenu.setString(2, username);
                updatemenu.setString(3, alamat);
                updatemenu.setString(4, password);
                updatemenu.setString(5, no);
                updatemenu.executeUpdate();
                JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
                kasir2();
                panel_utama.removeAll();
                panel_utama.add(new UserKasir());
                panel_utama.repaint();
                panel_utama.revalidate();
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error mengupdate data: " + e.getMessage());
        }

    }

    private void prosesGambar(File file) {
        try {
            // Baca file sebagai byte array
            byte[] imageBytes = Files.readAllBytes(file.toPath());

            // Buat ImageIcon untuk preview
            ImageIcon imageIcon = new ImageIcon(imageBytes);

            // Resize gambar jika terlalu besar
            if (imageIcon.getIconWidth() > 300) {
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(300, -1, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
            }

            // Tampilkan preview (opsional)
            tampilkanPreview(imageIcon);

            // Simpan ke database
            simpanKeDatabase(imageBytes, file.getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error memproses gambar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void prosesGambar1(File file) {
        try {
            // Baca file sebagai byte array
            byte[] imageBytes = Files.readAllBytes(file.toPath());

            // Buat ImageIcon untuk preview
            ImageIcon imageIcon = new ImageIcon(imageBytes);

            // Resize gambar jika terlalu besar
            if (imageIcon.getIconWidth() > 300) {
                Image image = imageIcon.getImage();
                Image newimg = image.getScaledInstance(300, -1, java.awt.Image.SCALE_SMOOTH);
                imageIcon = new ImageIcon(newimg);
            }

            // Tampilkan preview (opsional)
            tampilkanPreview1(imageIcon);

            // Simpan ke database
            simpanKeDatabase1(imageBytes, file.getName());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this,
                    "Error memproses gambar: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tampilkanPreview(ImageIcon imageIcon) {
        text_gambar = new JLabel(imageIcon);
    }

    private void tampilkanPreview1(ImageIcon imageIcon) {
        text_gambar1 = new JLabel(imageIcon);
    }

    private void simpanKeDatabase(byte[] imageBytes, String fileName) {
        // Gunakan try-with-resources untuk koneksi database
        try (
                Connection conn = (Connection) Config.ConfigDB(); PreparedStatement pstmt = conn.prepareStatement("UPDATE user SET foto = ? WHERE kd_user = 'KU_02'")) {

            pstmt.setBytes(1, imageBytes);
// Pastikan currentId sudah dideklarasikan

            int result = pstmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "Gambar berhasil disimpan Ke Database",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                try {
                    kasir1();
                } catch (Exception e) {
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error menyimpan ke database: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
    }

    private void simpanKeDatabase1(byte[] imageBytes, String fileName) {
        // Gunakan try-with-resources untuk koneksi database
        try (
                Connection conn = (Connection) Config.ConfigDB(); PreparedStatement pstmt = conn.prepareStatement("UPDATE user SET foto = ? WHERE kd_user = 'KU_03'")) {

            pstmt.setBytes(1, imageBytes);
// Pastikan currentId sudah dideklarasikan

            int result = pstmt.executeUpdate();
            if (result > 0) {
                JOptionPane.showMessageDialog(this,
                        "Gambar berhasil disimpan Ke Database",
                        "Sukses",
                        JOptionPane.INFORMATION_MESSAGE);
                try {
                    kasir2();
                } catch (Exception e) {
                }

            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error menyimpan ke database: " + e.getMessage(),
                    "Error",
                    JOptionPane.ERROR_MESSAGE);
        }
        prosesGambar(selectedFile);
    }

    private void kasir1() throws IOException {
        try {
            String query = "SELECT * FROM user where kd_user = 'KU_02'";
            // Ganti nama_tabel dan kolom_stok sesuai dengan struktur database Anda
            java.sql.Connection con = (Connection) Config.ConfigDB();
            //java.sql.ResultSet rs = pst.executeQuery(sql);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String s_nama = rs.getString("nama");
                String username = rs.getString("username");
                String alamat = rs.getString("alamat");
                String pw = rs.getString("password");
                String no_telepon = rs.getString("phone");
                text_nama.setText(s_nama);
                text_username.setText(username);
                text_alamat.setText(alamat);
                text_pw.setText(pw);
                text_no.setText(no_telepon);

                byte[] imgData = rs.getBytes("foto"); // Sesuaikan nama kolom gambar di database
                if (imgData != null) {
                    // Konversi data gambar menjadi ImageIcon
                    InputStream is = new ByteArrayInputStream(imgData);
                    BufferedImage bufferedImage = ImageIO.read(is);
                    ImageIcon icon = new ImageIcon(bufferedImage);

                    // Tampilkan gambar pada JLabel
                    text_gambar.setIcon(icon); // Pastikan `gambar_1` adalah JLabel
                } else {
                    text_gambar.setText("Gambar tidak tersedia");
                }
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error mengambil data: " + e.getMessage());
        }
    }

    private void kasir2() throws IOException {
        try {
            String query = "SELECT * FROM user where kd_user = 'KU_03'";
            // Ganti nama_tabel dan kolom_stok sesuai dengan struktur database Anda
            java.sql.Connection con = (Connection) Config.ConfigDB();
            //java.sql.ResultSet rs = pst.executeQuery(sql);
            Statement stmt = con.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            if (rs.next()) {
                String nama = rs.getString("nama");
                String username = rs.getString("username");
                String alamat = rs.getString("alamat");
                String pw = rs.getString("password");
                String no_telepon = rs.getString("phone");
                text_nama1.setText(nama);
                text_username1.setText(username);
                text_alamat1.setText(alamat);
                text_pw1.setText(pw);
                text_no1.setText(no_telepon);

                byte[] imgData = rs.getBytes("foto"); // Sesuaikan nama kolom gambar di database
                if (imgData != null) {
                    // Konversi data gambar menjadi ImageIcon
                    InputStream is = new ByteArrayInputStream(imgData);
                    BufferedImage bufferedImage = ImageIO.read(is);
                    ImageIcon icon = new ImageIcon(bufferedImage);

                    // Tampilkan gambar pada JLabel
                    text_gambar1.setIcon(icon); // Pastikan `gambar_1` adalah JLabel
                } else {
                    text_gambar1.setText("Gambar tidak tersedia");
                }
            }

            rs.close();
            stmt.close();
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error mengambil data: " + e.getMessage());
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Owner1;
    private javax.swing.JButton Owner2;
    private javax.swing.JButton btn_gambar;
    private javax.swing.JButton btn_gambar1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_utama;
    private javax.swing.JTextField t_path;
    private javax.swing.JTextField t_path1;
    private javax.swing.JTextField text_alamat;
    private javax.swing.JTextField text_alamat1;
    private javax.swing.JLabel text_edit;
    private javax.swing.JLabel text_edit1;
    private javax.swing.JLabel text_gambar;
    private javax.swing.JLabel text_gambar1;
    private javax.swing.JTextField text_nama;
    private javax.swing.JTextField text_nama1;
    private javax.swing.JTextField text_no;
    private javax.swing.JTextField text_no1;
    private javax.swing.JTextField text_pw;
    private javax.swing.JTextField text_pw1;
    private javax.swing.JTextField text_username;
    private javax.swing.JTextField text_username1;
    // End of variables declaration//GEN-END:variables
}
