
import java.awt.Color;
import java.sql.Connection;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.renderer.category.BarRenderer;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
//import com.raven.chart.ModelChart;
//import java.awt.Color;
/**
 *
 * @author acer
 */
public class FormLaporan extends javax.swing.JPanel {

    /**
     * Creates new form FormLaporan
     */
    public FormLaporan() {
        initComponents();
        setOpaque(false);
        buatGrafikPenghasilan();
//        init();
    }

    private void buatGrafikPenghasilan() {
        // Buat dataset untuk grafik
        CategoryDataset dataset = buatDataset();

        // Buat grafik tipe bar
        JFreeChart barChart = ChartFactory.createBarChart(
                "Grafik Penghasilan", // Judul grafik
                "Hari", // Label sumbu X
                "Penghasilan (Rp)", // Label sumbu Y
                dataset // Data untuk grafik
        );

        CategoryPlot plot = barChart.getCategoryPlot();  // Dapatkan plot dari grafik
        BarRenderer renderer = (BarRenderer) plot.getRenderer();
        renderer.setSeriesPaint(0, new Color(255, 255, 255, 150));
        renderer.setMaximumBarWidth(0.1);               // Atur lebar batang (20% dari lebar kategori)

        barChart.setBackgroundPaint(null); // Transparan
        barChart.getPlot().setBackgroundPaint(null); // Latar belakang plot transparan
        barChart.getPlot().setOutlinePaint(null); // Hilangkan garis batas plot

        // Masukkan grafik ke dalam JPanel
        ChartPanel chartPanel = new ChartPanel(barChart);

        chartPanel.setBackground(null); // Latar belakang panel transparan
        chartPanel.setOpaque(false);    // Hilangkan opacity panel
        chartPanel.setPreferredSize(new java.awt.Dimension(400, 300));
        chartPanel.setPreferredSize(panel_grafik.getSize()); // Sesuaikan ukuran
        panel_grafik.setLayout(new java.awt.BorderLayout());
        panel_grafik.add(chartPanel, java.awt.BorderLayout.CENTER);
        panel_grafik.validate();

    }

//    private CategoryDataset buatDataset() {
//        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
//
//        // Contoh data penghasilan
//        dataset.addValue(5000000, "Penghasilan", "Senin");
//        dataset.addValue(7000000, "Penghasilan", "Selasa");
//        dataset.addValue(6000000, "Penghasilan", "Rabu");
//        dataset.addValue(8000000, "Penghasilan", "Kamis");
//        dataset.addValue(7500000, "Penghasilan", "Jum'at");
//        dataset.addValue(7500000, "Penghasilan", "Sabtu");
//        dataset.addValue(7500000, "Penghasilan", "Minggu");
//        return dataset;
//    }
    private CategoryDataset buatDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        try {
                String sql = "SELECT hari, sum(total_transaksijual) as penghasilan FROM transaksi_jual group by hari ORDER BY FIELD(hari, 'Senin', 'Selasa', 'Rabu', 'Kamis', 'Jumat', 'Sabtu', 'Minggu')";
                Connection konek = new Config().ConfigDB(); 
                java.sql.PreparedStatement pst = konek.prepareStatement(sql);
                java.sql.ResultSet rs = pst.executeQuery(sql);

            while (rs.next() ){
                String hari = rs.getString("hari");
                double penghasilan = rs.getDouble("penghasilan");
                dataset.addValue(penghasilan, "Pendapatan Setiap Harinya", hari);
            }
            
        } catch (Exception e) {
            e.printStackTrace();
        }
        return dataset;
    }
//private void init() {
//        chart.addLegend("Pengeluaran", new Color(12, 84, 175), new Color(0, 108, 247));
//        chart.addData(new ModelChart("Senin", new double[]{500, 200, 80, 89}));
//        chart.addData(new ModelChart("Selasa", new double[]{600, 750, 90, 150}));
//        chart.addData(new ModelChart("Rabu", new double[]{200, 350, 460, 900}));
//        chart.addData(new ModelChart("Kamis", new double[]{480, 150, 750, 700}));
//        chart.addData(new ModelChart("Jumat", new double[]{350, 540, 300, 150}));
//        chart.addData(new ModelChart("Sabtu", new double[]{190, 280, 81, 200}));
//        chart.start();
//    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        bawah = new panelcustom();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        kanan3 = new panelcustom();
        jLabel5 = new javax.swing.JLabel();
        kanan2 = new panelcustom();
        jLabel4 = new javax.swing.JLabel();
        kanan1 = new panelcustom();
        jLabel3 = new javax.swing.JLabel();
        panel_grafik = new panelcustom();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        setLayout(new java.awt.CardLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bawah.setBackground(new java.awt.Color(164, 192, 239));
        bawah.setRoundBottomLeft(25);
        bawah.setRoundBottomRight(25);
        bawah.setRoundTopLeft(25);
        bawah.setRoundTopRight(25);

        jLabel6.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel6.setText("I.Transaksi Penjualan");

        jLabel7.setFont(new java.awt.Font("SansSerif", 1, 34)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("DETAIL PENJUALAN DAN PENGELUARAN");

        jLabel8.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel8.setText("Menu Makanan dan Minuman yang Terjual");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jLabel9.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel9.setText("Total Pendapatan Penjualan: Rp ");

        jLabel10.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel10.setText("II.Transaksi Pembelian Bahan Baku");

        jLabel11.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel11.setText("List Bahan Baku yang Dibeli");

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        jLabel12.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel12.setText("______________________________________________________________________________");

        jLabel13.setFont(new java.awt.Font("SansSerif", 1, 18)); // NOI18N
        jLabel13.setText("Total Pendapatan Pembelian: Rp ");

        javax.swing.GroupLayout bawahLayout = new javax.swing.GroupLayout(bawah);
        bawah.setLayout(bawahLayout);
        bawahLayout.setHorizontalGroup(
            bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bawahLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel12)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel8)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 809, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(55, Short.MAX_VALUE))
            .addGroup(bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bawahLayout.createSequentialGroup()
                    .addContainerGap(113, Short.MAX_VALUE)
                    .addComponent(jLabel7)
                    .addGap(103, 103, 103)))
        );
        bawahLayout.setVerticalGroup(
            bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bawahLayout.createSequentialGroup()
                .addGap(109, 109, 109)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 55, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel13)
                .addGap(16, 16, 16))
            .addGroup(bawahLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(bawahLayout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(jLabel7)
                    .addContainerGap(790, Short.MAX_VALUE)))
        );

        jPanel1.add(bawah, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 680, 920, 850));

        kanan3.setBackground(new java.awt.Color(164, 192, 239));
        kanan3.setRoundBottomLeft(30);
        kanan3.setRoundBottomRight(30);
        kanan3.setRoundTopLeft(30);
        kanan3.setRoundTopRight(30);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Pendapatan Bersih");

        javax.swing.GroupLayout kanan3Layout = new javax.swing.GroupLayout(kanan3);
        kanan3.setLayout(kanan3Layout);
        kanan3Layout.setHorizontalGroup(
            kanan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kanan3Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(56, 56, 56))
        );
        kanan3Layout.setVerticalGroup(
            kanan3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kanan3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel1.add(kanan3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 520, 240, 120));

        kanan2.setBackground(new java.awt.Color(164, 192, 239));
        kanan2.setRoundBottomLeft(30);
        kanan2.setRoundBottomRight(30);
        kanan2.setRoundTopLeft(30);
        kanan2.setRoundTopRight(30);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pendapatan Kotor");

        javax.swing.GroupLayout kanan2Layout = new javax.swing.GroupLayout(kanan2);
        kanan2.setLayout(kanan2Layout);
        kanan2Layout.setHorizontalGroup(
            kanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kanan2Layout.createSequentialGroup()
                .addContainerGap(60, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(56, 56, 56))
        );
        kanan2Layout.setVerticalGroup(
            kanan2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kanan2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel1.add(kanan2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 390, 240, 120));

        kanan1.setBackground(new java.awt.Color(0, 0, 51));
        kanan1.setRoundBottomLeft(30);
        kanan1.setRoundBottomRight(30);
        kanan1.setRoundTopLeft(30);
        kanan1.setRoundTopRight(30);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Pengeluran");

        javax.swing.GroupLayout kanan1Layout = new javax.swing.GroupLayout(kanan1);
        kanan1.setLayout(kanan1Layout);
        kanan1Layout.setHorizontalGroup(
            kanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kanan1Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(80, 80, 80))
        );
        kanan1Layout.setVerticalGroup(
            kanan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kanan1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jPanel1.add(kanan1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 260, 240, 120));

        panel_grafik.setBackground(new java.awt.Color(164, 192, 239));
        panel_grafik.setRoundBottomLeft(25);
        panel_grafik.setRoundBottomRight(25);
        panel_grafik.setRoundTopLeft(25);
        panel_grafik.setRoundTopRight(25);
        panel_grafik.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(panel_grafik, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 630, 380));
        jPanel1.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 150, 180, 40));

        jLabel2.setText("Tanggal");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, -1, -1));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(164, 192, 239));
        jLabel1.setText("LAPORAN");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, -1, -1));

        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/batik azure.png"))); // NOI18N
        jPanel1.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 770));

        add(jPanel1, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panelcustom bawah;
    private javax.swing.JLabel bg;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private panelcustom kanan1;
    private panelcustom kanan2;
    private panelcustom kanan3;
    private panelcustom panel_grafik;
    // End of variables declaration//GEN-END:variables
}
