
import com.formdev.flatlaf.FlatLightLaf;
import java.awt.Color;
import java.awt.Component;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Insets;
import java.awt.RenderingHints;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.AbstractButton;
import javax.swing.BorderFactory;
import javax.swing.JComponent;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.Timer;
import javax.swing.UIManager;
import javax.swing.border.AbstractBorder;
import javax.swing.plaf.basic.BasicButtonUI;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author acer
 */
public class FormMenu extends javax.swing.JFrame {

    private String i;
    public String menentukan = "menu";

    /**
     * Creates new form FormMenu
     */
//    public FormMenu(String a) {
//        this.i = a;
//
//        // Tampilkan posisi di label atau lakukan sesuatu dengan posisi
//        System.out.println(i);
//
//        // Kontrol akses berdasarkan posisi
//        //kontrolAksesPosisi();
//    }
    public FormMenu(String a) {
        initComponents();
        this.i = a;
        System.out.println("posisi di form " + i);
        FlatLightLaf.setup();

        UIManager.put("Button.arc", 50);

        panel_utama.removeAll();
        panel_utama.add(new Makanan());
        panel_utama.repaint();
        panel_utama.revalidate();
        try {
            UIManager.setLookAndFeel(new FlatLightLaf());
            SwingUtilities.updateComponentTreeUI(this);
        } catch (Exception e) {
            e.printStackTrace();
        }
        SwingUtilities.invokeLater(() -> {
            btn_menu.setVisible(true);
            btn_bahan.setVisible(true);
            btn_user.setVisible(true);
            btn_pembayaran.setVisible(true);
            btn_laporan.setVisible(true);

        });
        panel_kiri.setOpaque(false); // Agar sudut transparan
        panel_kiri.setBorder(new RoundedBorder(10));
        panel_utama.setOpaque(false); // Agar sudut transparan
        panel_utama.setBorder(new RoundedBorder(10));
    }

    // Kelas Border Kustom
    static class RoundedBorder extends AbstractBorder {

        private final int radius;

        public RoundedBorder(int radius) {
            this.radius = radius;
        }

        @Override
        public void paintBorder(Component c, Graphics g, int x, int y, int width, int height) {
            Graphics2D g2 = (Graphics2D) g;
            g2.setRenderingHint(RenderingHints.KEY_ANTIALIASING, RenderingHints.VALUE_ANTIALIAS_ON);
            g2.setColor(c.getBackground());
            g2.fillRoundRect(x, y, width - 1, height - 1, radius, radius);
            g2.setColor(Color.GRAY); // Warna border
            g2.drawRoundRect(x, y, width - 1, height - 1, radius, radius);
        }

        @Override
        public Insets getBorderInsets(Component c) {
            return new Insets(radius + 1, radius + 1, radius + 1, radius + 1);
        }

        @Override
        public boolean isBorderOpaque() {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new javax.swing.JPanel();
        panel_kiri = new javax.swing.JPanel();
        btn_menu = new javax.swing.JButton();
        btn_bahan = new javax.swing.JButton();
        btn_user = new javax.swing.JButton();
        btn_pembayaran = new javax.swing.JButton();
        btn_laporan = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        panel_utama.setMaximumSize(new java.awt.Dimension(990, 770));
        panel_utama.setMinimumSize(new java.awt.Dimension(990, 770));
        panel_utama.setLayout(new java.awt.CardLayout());
        getContentPane().add(panel_utama, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 0, 990, 770));

        panel_kiri.setBackground(new java.awt.Color(164, 192, 239));

        btn_menu.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btn_menu.setForeground(new java.awt.Color(164, 192, 239));
        btn_menu.setText("Menu");
        btn_menu.setBorderPainted(false);
        btn_menu.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_menu.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_menu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_menuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_menuMouseExited(evt);
            }
        });
        btn_menu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_menuActionPerformed(evt);
            }
        });

        btn_bahan.setBackground(new java.awt.Color(164, 192, 239));
        btn_bahan.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btn_bahan.setForeground(new java.awt.Color(255, 255, 255));
        btn_bahan.setText("Bahan Baku");
        btn_bahan.setBorderPainted(false);
        btn_bahan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_bahan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_bahan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_bahanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_bahanMouseExited(evt);
            }
        });
        btn_bahan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_bahanActionPerformed(evt);
            }
        });

        btn_user.setBackground(new java.awt.Color(164, 192, 239));
        btn_user.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btn_user.setForeground(new java.awt.Color(255, 255, 255));
        btn_user.setText("User");
        btn_user.setBorderPainted(false);
        btn_user.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_user.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_userMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_userMouseExited(evt);
            }
        });
        btn_user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_userActionPerformed(evt);
            }
        });

        btn_pembayaran.setBackground(new java.awt.Color(164, 192, 239));
        btn_pembayaran.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btn_pembayaran.setForeground(new java.awt.Color(255, 255, 255));
        btn_pembayaran.setText("Pembayaran");
        btn_pembayaran.setBorderPainted(false);
        btn_pembayaran.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_pembayaran.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_pembayaran.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_pembayaranMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_pembayaranMouseExited(evt);
            }
        });
        btn_pembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_pembayaranActionPerformed(evt);
            }
        });

        btn_laporan.setBackground(new java.awt.Color(164, 192, 239));
        btn_laporan.setFont(new java.awt.Font("Segoe UI", 1, 26)); // NOI18N
        btn_laporan.setForeground(new java.awt.Color(255, 255, 255));
        btn_laporan.setText("Laporan");
        btn_laporan.setBorderPainted(false);
        btn_laporan.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_laporan.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        btn_laporan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btn_laporanMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btn_laporanMouseExited(evt);
            }
        });
        btn_laporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_laporanActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/logo warung djoglo sri terbaru PUTIH.png"))); // NOI18N

        javax.swing.GroupLayout panel_kiriLayout = new javax.swing.GroupLayout(panel_kiri);
        panel_kiri.setLayout(panel_kiriLayout);
        panel_kiriLayout.setHorizontalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGroup(panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_pembayaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_laporan, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
            .addComponent(btn_bahan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(btn_user, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panel_kiriLayout.setVerticalGroup(
            panel_kiriLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_kiriLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btn_menu, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_bahan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_user, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_pembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_laporan, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(256, Short.MAX_VALUE))
        );

        getContentPane().add(panel_kiri, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 380, 770));

        setSize(new java.awt.Dimension(1380, 775));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btn_menuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseEntered

    }//GEN-LAST:event_btn_menuMouseEntered

    private void btn_bahanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_bahanActionPerformed
        menentukan = "bahan";
        btn_user.setBackground(new Color(164, 192, 239));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_menu.setBackground(new Color(164, 192, 239));
        btn_menu.setForeground(new Color(255, 255, 255));
        btn_pembayaran.setBackground(new Color(164, 192, 239));
        btn_pembayaran.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(164, 192, 239));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_bahan.setBackground(new Color(255, 255, 255));
        btn_bahan.setForeground(new Color(164, 192, 239));

        panel_utama.removeAll();
        panel_utama.add(new BahanBaku());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_bahanActionPerformed

    private void btn_menuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_menuActionPerformed
        menentukan = "menu";
        btn_user.setBackground(new Color(164, 192, 239));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_bahan.setBackground(new Color(164, 192, 239));
        btn_bahan.setForeground(new Color(255, 255, 255));
        btn_pembayaran.setBackground(new Color(164, 192, 239));
        btn_pembayaran.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(164, 192, 239));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_menu.setBackground(new Color(255, 255, 255));
        btn_menu.setForeground(new Color(164, 192, 239));

        panel_utama.removeAll();
        panel_utama.add(new Makanan());
        panel_utama.repaint();
        panel_utama.revalidate();
    }//GEN-LAST:event_btn_menuActionPerformed

    private void btn_userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_userActionPerformed
        if (i.equals("Kasir")) {
            warning a = new warning();
            a.setVisible(true);
            a.setAnimationSpeed(8);
            a.showSlideUp();
        } else {
            panel_utama.removeAll();
            panel_utama.add(new UserKasir());
            panel_utama.repaint();
            panel_utama.revalidate();

            btn_menu.setBackground(new Color(164, 192, 239));
            btn_menu.setForeground(new Color(255, 255, 255));
            btn_bahan.setBackground(new Color(1164, 192, 239));
            btn_bahan.setForeground(new Color(255, 255, 255));
            btn_pembayaran.setBackground(new Color(164, 192, 239));
            btn_pembayaran.setForeground(new Color(255, 255, 255));
            btn_laporan.setBackground(new Color(164, 192, 239));
            btn_laporan.setForeground(new Color(255, 255, 255));

            btn_user.setBackground(new Color(255, 255, 255));
            btn_user.setForeground(new Color(164, 192, 239));
        }


    }//GEN-LAST:event_btn_userActionPerformed

    private void btn_pembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_pembayaranActionPerformed
        panel_utama.removeAll();
        panel_utama.add(new Penjualan());
        panel_utama.repaint();
        panel_utama.revalidate();
        menentukan = "pembayaran";
        btn_menu.setBackground(new Color(164, 192, 239));
        btn_menu.setForeground(new Color(255, 255, 255));
        btn_bahan.setBackground(new Color(164, 192, 239));
        btn_bahan.setForeground(new Color(255, 255, 255));
        btn_user.setBackground(new Color(164, 192, 239));
        btn_user.setForeground(new Color(255, 255, 255));
        btn_laporan.setBackground(new Color(164, 192, 239));
        btn_laporan.setForeground(new Color(255, 255, 255));

        btn_pembayaran.setBackground(new Color(255, 255, 255));
        btn_pembayaran.setForeground(new Color(164, 192, 239));
    }//GEN-LAST:event_btn_pembayaranActionPerformed

    private void btn_laporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_laporanActionPerformed
        if (i.equals("Kasir")) {
            warning a = new warning();
            a.setVisible(true);
            a.setAnimationSpeed(8);
            a.showSlideUp();
        } else {
            panel_utama.removeAll();
            panel_utama.add(new FormLaporan());
            panel_utama.repaint();
            panel_utama.revalidate();
            btn_menu.setBackground(new Color(164, 192, 239));
            btn_menu.setForeground(new Color(255, 255, 255));
            btn_bahan.setBackground(new Color(164, 192, 239));
            btn_bahan.setForeground(new Color(255, 255, 255));
            btn_user.setBackground(new Color(164, 192, 239));
            btn_user.setForeground(new Color(255, 255, 255));
            btn_pembayaran.setBackground(new Color(164, 192, 239));
            btn_pembayaran.setForeground(new Color(255, 255, 255));
            menentukan = "laporan";
            btn_laporan.setBackground(new Color(255, 255, 255));
            btn_laporan.setForeground(new Color(164, 192, 239));
        }

    }//GEN-LAST:event_btn_laporanActionPerformed

    private void btn_laporanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseEntered

    }//GEN-LAST:event_btn_laporanMouseEntered

    private void btn_pembayaranMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembayaranMouseEntered

    }//GEN-LAST:event_btn_pembayaranMouseEntered

    private void btn_userMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseEntered

    }//GEN-LAST:event_btn_userMouseEntered

    private void btn_bahanMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bahanMouseEntered

    }//GEN-LAST:event_btn_bahanMouseEntered

    private void btn_menuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_menuMouseExited

    }//GEN-LAST:event_btn_menuMouseExited

    private void btn_bahanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_bahanMouseExited

    }//GEN-LAST:event_btn_bahanMouseExited

    private void btn_userMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_userMouseExited

    }//GEN-LAST:event_btn_userMouseExited

    private void btn_pembayaranMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_pembayaranMouseExited

    }//GEN-LAST:event_btn_pembayaranMouseExited

    private void btn_laporanMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_laporanMouseExited

    }//GEN-LAST:event_btn_laporanMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormMenu.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                FormMenu coba = new FormMenu(String a);
//                coba.setVisible(true);
                //new FormMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_bahan;
    private javax.swing.JButton btn_laporan;
    private javax.swing.JButton btn_menu;
    private javax.swing.JButton btn_pembayaran;
    private javax.swing.JButton btn_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel panel_kiri;
    private javax.swing.JPanel panel_utama;
    // End of variables declaration//GEN-END:variables
}
