/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.data.category.CategoryDataset;
import org.jfree.data.category.DefaultCategoryDataset;
/**
 *
 * @author acer
 */
public class grapik_pengeluaran extends javax.swing.JPanel {

     grapik_pengeluaran() {
        initComponents();
        buatGrafik();
    }
private void buatGrafik() {
        // Buat dataset untuk grafik
        CategoryDataset dataset = buatDataset();

        // Buat grafik tipe bar
        JFreeChart barChart = ChartFactory.createBarChart(
                "Grafik Penghasilan",       // Judul grafik
                "Bulan",                   // Label sumbu X
                "Penghasilan (Rp)",        // Label sumbu Y
                dataset                    // Data untuk grafik
        );

        // Masukkan grafik ke dalam JPanel
        ChartPanel chartPanel = new ChartPanel(barChart);
        chartPanel.setPreferredSize(new java.awt.Dimension(800, 600));
        this.setLayout(new java.awt.BorderLayout());
        this.add(chartPanel, java.awt.BorderLayout.CENTER);
        this.validate();
    }

    private CategoryDataset buatDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();

        // Contoh data penghasilan
        dataset.addValue(5000000, "Penghasilan", "Januari");
        dataset.addValue(7000000, "Penghasilan", "Februari");
        dataset.addValue(6000000, "Penghasilan", "Maret");
        dataset.addValue(8000000, "Penghasilan", "April");
        dataset.addValue(7500000, "Penghasilan", "Mei");

        return dataset;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_utama = new panelcustom();

        setLayout(new java.awt.CardLayout());

        panel_utama.setBackground(new java.awt.Color(255, 51, 102));
        panel_utama.setRoundBottomLeft(25);
        panel_utama.setRoundBottomRight(25);
        panel_utama.setRoundTopLeft(25);
        panel_utama.setRoundTopRight(25);
        panel_utama.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        add(panel_utama, "card2");
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private panelcustom panel_utama;
    // End of variables declaration//GEN-END:variables
}
